### ISSUE TITLE
question:

### ISSUE THREAD

**Issue by liberateyourtech** [roboes/odoo-woocommerce-sync#2]
Hi Roberto!

I found you when searching for odoo woocommerce connectors and after trying a few out I liked yours, and appreciate the amount of work you have put in while making it open source!

I have a couple of questions please...
I am missing the 'deliveries' option on sales orders which i really need to set up and track shipping. I see this with other connectors, is this feature not connected or am I missing something else?

Finally do you plan to make versions available for odoo 17 or 18? I understand it might be a major re write? 

Many thanks!

L

**Comment by roboes** [comment]
Hi @liberateyourtech, thank you for your message.

I'm not entirely sure what you mean by the "deliveries" option on sales orders - specifically in the context of setting up and tracking shipping. Could you perhaps share an article or some screenshots to help clarify? Also, does this feature require any additional add-ons (and if so, which ones)?

As for the update to Odoo 17 and 18: I can’t give a specific timeline, but it's on the roadmap if time allows. Right now, I'm waiting for several Odoo Community Association (OCA) add-ons - both required and optional - to be updated for those versions. You can find the list of OCA add-ons used in the [readme.md](https://github.com/roboes/odoo-woocommerce-sync/blob/16.0/readme.md) file. One example, `queue_job`, already appears to support the newer versions.
The WooCommerce connector is based on the `woocommerce` Python package, which I don't expect to cause any major issues when porting to newer Odoo versions.

Hope this answers your questions!

**Comment by liberateyourtech** [comment]
Thanks for the quick reply!

Odoo creates a 'Delivery Order' when a sales order is created, each line is linked to a line on the sales order
When using other connectors to import sales orders from my woo store I see the Delivery tab in the top right, which links through to a delivery order for shipping (screen shot below)

![Image](https://github.com/user-attachments/assets/b57869d9-677b-442b-8f60-71e1ee256008)

I dont see this with your connector (but i do get more additional data and dashboards populate which is great)
I notice other connectors have both 'delivery' and 'purchase' listed in their depends in the manifest__.py

Re later versions of odoo I will keep following, thanks again!

**Comment by roboes** [comment]
I'm relatively new to Odoo and wasn't aware of the "Delivery Methods" feature, so I have just added the logic to import WooCommerce shipping methods into Odoo.

To enable this in Odoo, update the add-on and go to: `Home Menu` > `Settings` > `Inventory` > `Shipping` > Enable `Delivery Methods`.

Here's how the new logic works:
1) Retrieve or Create Delivery Carrier: The new `odoo_delivery_carrier_create_or_retrieve()` function checks if a shipping method from WooCommerce already exists in Odoo. If not, it creates a new "delivery carrier" and associates it with a product (a service product for the shipping method).
2) Assign Delivery Carrier to Sales Order: Once the delivery carrier is created or found, the shipping method is linked to the Odoo sale order using the native [`set_delivery_line()`](https://github.com/odoo/odoo/blob/172473ee1cc7fdf1119dc0f97272176808f9746f/addons/delivery/models/sale_order.py#L59) function, which sets the carrier for the order.

This ensures that WooCommerce shipping methods are properly imported and assigned to orders in Odoo.

Please let me know if this implementation adds the feature you were expecting! :) Also, remember to test the add-on in a test environment.

Just a heads-up: currently, there is no synchronization between the sales order status in Odoo and WooCommerce.

**Comment by liberateyourtech** [comment]
Thanks for the quick work Roberto!

I now get the delivery listed in the sales order! (although it appears as the first line before the actual product
However I dont see a delivery order created, or the button that links to it in the sales order

If you create an sales order manually and add the shipping item it creates the delivery order, which you can see under Inventory > Overview > Delivery Orders

![Image](https://github.com/user-attachments/assets/e8062e00-99bc-4f77-9d46-a86f3b3b776d)

I hope the screenshot helps to explain it more technically

Thanks again!

**Comment by roboes** [comment]
Thanks for your feedback! It looks like the logic is heading in the right direction.

I've updated the code once more, and the workflow is now as follows: Create Order → Add Products → Set Shipping → Confirm → Create Delivery.

Could you please test it again, ideally with a fresh order import?

**Comment by liberateyourtech** [comment]
Tested again on a fresh database. Not quite! The shipping line shows under the product in the sales order now, but all of the products in the sales order are one product 'WooCommerce Product Placeholder' not the actual imported products (this woocommerce place holder is also an archived product, it took me a moment to find it)

I still dont see any delivery orders created or a Deliveries button but I am assuming that may have something to do with the products not matching the sales order

Products are imported (if they have an SKU number) and I do use variations which are showing. Some products import without the attribute 'can be sold' but I am not sure why yet. I can set it no problem in odoo

I have tried re importing, deleting records and re importing in stages but still the same result

Thanks again for your time Roberto, much appreciated!

**Comment by roboes** [comment]
Thank you for your updated feedback!

Regarding the "WooCommerce Product Placeholder", this behavior is expected and can be modified in the configuration settings. Please refer to [this section](https://github.com/roboes/odoo-woocommerce-sync#configuration) for detailed instructions on how to make the change.

Could you test enabling it to see if the import works as expected? If successful, I might consider changing the default setting to enable this for both Guest Customers and Line Items Product mapping.

**Comment by liberateyourtech** [comment]
Thanks for the quick reply! I tested again with both map products and map guest customers settings enabled but all of my sales orders still show the product placeholder
Reading the instructions again, do I need products already in Odoo for the import to map to? I tried to import just products first and then orders but still the same result
Let me know what else to check on my configs, thank you!

**Comment by roboes** [comment]
Apologies for the delayed response.

For the mapping logic to work correctly, WooCommerce customers and products must already be imported into Odoo. If you choose to import Products, Product Variants, and Customers, the process will follow this mapping logic:

![Image](https://github.com/user-attachments/assets/f62e7796-f8e2-4629-b405-adac9ccffc71)

I've reviewed the code and confirmed that the mapping wasn't functioning as expected. I've made further updates - could you please test it again, ideally using a clean database import?

Please note there might be a slight delay in my responses.

Thanks!

**Comment by liberateyourtech** [comment]
Thank you! Delivery orders are now showing correctly and shipping product is listed after the product!

I do have a separate issue: only orders for my variable products are importing. Simple product orders are not. error in the logs looks like this for each order that fails

> psycopg2.errors.CheckViolation: new row for relation "sale_order_line" violates check constraint "sale_order_line_accountable_required_fields"
DETAIL:  Failing row contains (811, 552, 10, 1, 2, 1257, 2, null, 12, null, 2, 2, sale, null, manual, null, null, UPGRADE YOUR PIXEL TO GRAPHENEOS, 1.00, 100.00, 0.00, 100.00, 100.00, 100.00, 100.00, 100.00, 0.00, null, null, null, null, null, null, 2025-05-10 08:53:41.143664, 2025-05-10 08:53:41.143664, 0, 0, 0, null, null, null, null, f, 1, https://liberateyourtech.com, 291, UPGRADE YOUR PIXEL TO GRAPHENEOS, 12913, 0, null, DEGOO-PIXGOS, kg, [], [], 100, 0, 100, 0, 100, null, null).

2025-05-10 08:53:41,423 143 ERROR odoo16test odoo.sql_db: bad query: INSERT INTO "sale_order_line" ("company_id", "create_date", "create_uid", "currency_id", "customer_lead", "discount", "display_type", "is_delivery", "name", "order_id", "order_partner_id", "price_reduce", "price_reduce_taxexcl", "price_reduce_taxinc", "price_subtotal", "price_tax", "price_total", "price_unit", "product_id", "product_packaging_id", "product_packaging_qty", "product_uom", "product_uom_qty", "qty_delivered", "qty_delivered_method", "salesman_id", "sequence", "state", "woocommerce_order_line_item_id", "woocommerce_order_line_item_meta_data", "woocommerce_order_line_item_name", "woocommerce_order_line_item_price", "woocommerce_order_line_item_product_id", "woocommerce_order_line_item_quantity", "woocommerce_order_line_item_sku", "woocommerce_order_line_item_subtotal", "woocommerce_order_line_item_subtotal_tax", "woocommerce_order_line_item_tax_class", "woocommerce_order_line_item_taxes", "woocommerce_order_line_item_total", "woocommerce_order_line_item_total_tax", "woocommerce_order_line_item_variation_id", "woocommerce_order_line_item_weight_unit", "woocommerce_order_line_site_url", "write_date", "write_uid") VALUES (1, '2025-05-10 08:53:41.292283', 2, 2, 0.0, '0.00', NULL, false, 'LINEAGE GALAXY S6 Lite TABLET', 553, 1003, '489.00', '489.00', '489.00', '489.00', 0.0, '489.00', '489.00', NULL, NULL, 0.0, 12, '1.00', '0.00', 'manual', 2, 10, 'sale', '278', '[{''id'': 2203, ''key'': ''colour'', ''value'': ''Silver'', ''display_key'': ''colour'', ''display_value'': ''Silver''}, {''id'': 2204, ''key'': ''memory-size'', ''value'': ''128GB'', ''display_key'': ''memory-size'', ''display_value'': ''128GB''}]', 'LINEAGE GALAXY S6 Lite TABLET', 489.0, '12824', 1, 'S6TABLOS', 489.0, 0.0, NULL, '[]', 489.0, 0.0, '0', 'kg', 'https://liberateyourtech.com', '2025-05-10 08:53:41.292283', 2) RETURNING "id"
ERROR: new row for relation "sale_order_line" violates check constraint "sale_order_line_accountable_required_fields"
DETAIL:  Failing row contains (812, 553, 10, 1, 2, 1003, 2, null, 12, null, 2, 2, sale, null, manual, null, null, LINEAGE GALAXY S6 Lite TABLET, 1.00, 489.00, 0.00, 489.00, 489.00, 489.00, 489.00, 489.00, 0.00, null, null, null, null, null, null, 2025-05-10 08:53:41.292283, 2025-05-10 08:53:41.292283, 0, 0, 0, null, null, null, null, f, 1, https://liberateyourtech.com, 278, LINEAGE GALAXY S6 Lite TABLET, 12824, 0, null, S6TABLOS, kg, [], [{'id': 2203, 'key': 'colour', 'value': 'Silver', 'display_key':..., 489, 0, 489, 0, 489, null, null).

I have checked SKUs exist and the product has successfully imported into odoo. I cant see any other obvious differences in the products

Please let me know what else to check or info to give

Thanks again for the great add on! Way better than most on the addon store!

**Comment by roboes** [comment]
Apologies again for the delayed response.

I believe I have identified why the product mapping in order line items was working only for variable products and not for simple products. Could you please test it again, preferably on a clean database import?

I’m really glad to hear that this add-on is useful to you! Since I’m still relatively new to Odoo and haven't tested the (paid) add-ons available on the [Odoo Apps Store](https://apps.odoo.com/apps), I don't have a direct comparison point for you.

**Comment by roboes** [comment]
Hi @liberateyourtech,

Were you able to test the latest code? I've started updating the codebase to support initial Odoo 18 compatibility and to make future migrations smoother (see [changelog](https://github.com/roboes/odoo-woocommerce-sync/blob/16.0/changelog.md)). It's still in the early stages, so your testing would be incredibly helpful - especially given your experience with similar Odoo add-ons.

Your feedback will for sure help shape and improve the add-on's functionality.

Thanks!

**Comment by roboes** [comment]
Closed due to inactivity.
